export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAIL = 'CREATE_COURSE_FAIL';
export const CREATE_ROOM_FAIL = 'CREATE_ROOM_FAIL';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_COURSE_SESSION_SUCCESS = 'CREATE_COURSE_SESSION_SUCCESS';
export const CREATE_COURSE_SESSION_FAIL = 'CREATE_COURSE_SESSION_FAIL';